#!/usr/bin/env python3
"""Plot the explicit FreeFem meshes used by the Cocquet irregular-mesh study.

Unlike the structured siblings, this experiment loads unstructured Delaunay
triangulations from disk (data/meshes/freefem/*.msh, generated by
create_paper_meshes.edp). One PNG per .msh file is written to results/meshes/,
with the inlet/outlet/wall boundary edges coloured and the paper's h = sqrt(2)/N
annotated alongside the solver's measured average h_K.

Usage:
    python plot_mesh.py                # render every .msh in the freefem dir
    python plot_mesh.py --show         # display the first interactively
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "..", "tools", "mesh_viz"))
import _wrapper_common as wc  # noqa: E402

MSH_DIR = os.path.join(HERE, "data", "meshes", "freefem")
OUT_DIR = os.path.join(HERE, "results", "meshes")

if __name__ == "__main__":
    wc.run_freefem(MSH_DIR, OUT_DIR, sys.argv[1:])
