using Gridap
domain = (0, 1, 0, 1)
model = CartesianDiscreteModel(domain, (2, 2))
refe = ReferenceFE(lagrangian, VectorValue{2,Float64}, 1)
V = TestFESpace(model, refe)
u(x) = VectorValue(x[1]^2, x[1]*x[2])
uh = interpolate_everywhere(u, V)
x0 = Point(0.5, 0.5)
grad_val = evaluate(∇(uh), x0)
println("∇(u) = ", grad_val)
println("u(x0) = ", u(x0))
println("∇(u) ⋅ u = ", grad_val ⋅ u(x0))
println("∇(u)' ⋅ u = ", transpose(grad_val) ⋅ u(x0))
